name: tests

on:
  push:
  pull_request:

jobs:
  bats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bats-core/bats-action@3.0.0
      - run: bats tests/forge.bats
